# Generated by Django 4.2.10 on 2024-02-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='Walikelas',
        ),
    ]
