# Generated by Django 4.2.10 on 2024-02-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mapel_id_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nama_kelas',
            field=models.CharField(max_length=30),
        ),
    ]
