# Generated by Django 4.2.10 on 2024-02-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_kelas_nama_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='id_kelas',
        ),
    ]
